function TweakServices {
    try {
        $services = @(
            @{Name="AJRouter"; StartupType="Disabled"},
            @{Name="ALG"; StartupType="Manual"},
            @{Name="AppIDSvc"; StartupType="Manual"},
            @{Name="AppMgmt"; StartupType="Manual"},
            @{Name="AppReadiness"; StartupType="Manual"},
            @{Name="AppVClient"; StartupType="Disabled"},
            @{Name="AppXSvc"; StartupType="Manual"},
            @{Name="Appinfo"; StartupType="Manual"},
            @{Name="AssignedAccessManagerSvc"; StartupType="Disabled"},
            @{Name="AudioEndpointBuilder"; StartupType="Automatic"},
            @{Name="AudioSrv"; StartupType="Automatic"},
            @{Name="Audiosrv"; StartupType="Automatic"},
            @{Name="AxInstSV"; StartupType="Manual"},
            @{Name="BDESVC"; StartupType="Manual"},
            @{Name="BFE"; StartupType="Automatic"},
            @{Name="BITS"; StartupType="AutomaticDelayedStart"},
            @{Name="BTAGService"; StartupType="Manual"},
            @{Name="BrokerInfrastructure"; StartupType="Automatic"},
            @{Name="Browser"; StartupType="Manual"},
            @{Name="BthAvctpSvc"; StartupType="Automatic"},
            @{Name="BthHFSrv"; StartupType="Automatic"},
            @{Name="CDPSvc"; StartupType="Manual"},
            @{Name="COMSysApp"; StartupType="Manual"},
            @{Name="CertPropSvc"; StartupType="Manual"},
            @{Name="ClipSVC"; StartupType="Manual"},
            @{Name="CoreMessagingRegistrar"; StartupType="Automatic"},
            @{Name="CryptSvc"; StartupType="Automatic"},
            @{Name="CscService"; StartupType="Manual"},
            @{Name="DPS"; StartupType="Automatic"},
            @{Name="DcomLaunch"; StartupType="Automatic"},
            @{Name="DcpSvc"; StartupType="Manual"},
            @{Name="DevQueryBroker"; StartupType="Manual"},
            @{Name="DeviceAssociationService"; StartupType="Manual"},
            @{Name="DeviceInstall"; StartupType="Manual"},
            @{Name="Dhcp"; StartupType="Automatic"},
            @{Name="DiagTrack"; StartupType="Disabled"},
            @{Name="DialogBlockingService"; StartupType="Disabled"},
            @{Name="DispBrokerDesktopSvc"; StartupType="Automatic"},
            @{Name="DisplayEnhancementService"; StartupType="Manual"},
            @{Name="DmEnrollmentSvc"; StartupType="Manual"},
            @{Name="Dnscache"; StartupType="Automatic"},
            @{Name="EFS"; StartupType="Manual"},
            @{Name="EapHost"; StartupType="Manual"},
            @{Name="EntAppSvc"; StartupType="Manual"},
            @{Name="EventLog"; StartupType="Automatic"},
            @{Name="EventSystem"; StartupType="Automatic"},
            @{Name="FDResPub"; StartupType="Manual"},
            @{Name="Fax"; StartupType="Manual"},
            @{Name="FontCache"; StartupType="Automatic"},
            @{Name="FrameServer"; StartupType="Manual"},
            @{Name="FrameServerMonitor"; StartupType="Manual"},
            @{Name="GraphicsPerfSvc"; StartupType="Manual"},
            @{Name="HomeGroupListener"; StartupType="Manual"},
            @{Name="HomeGroupProvider"; StartupType="Manual"},
            @{Name="HvHost"; StartupType="Manual"},
            @{Name="IEEtwCollectorService"; StartupType="Manual"},
            @{Name="IKEEXT"; StartupType="Manual"},
            @{Name="InstallService"; StartupType="Manual"},
            @{Name="InventorySvc"; StartupType="Manual"},
            @{Name="IpxlatCfgSvc"; StartupType="Manual"},
            @{Name="KeyIso"; StartupType="Automatic"},
            @{Name="KtmRm"; StartupType="Manual"},
            @{Name="LSM"; StartupType="Automatic"},
            @{Name="LanmanServer"; StartupType="Automatic"},
            @{Name="LanmanWorkstation"; StartupType="Automatic"},
            @{Name="LicenseManager"; StartupType="Manual"},
            @{Name="LxpSvc"; StartupType="Manual"},
            @{Name="MSDTC"; StartupType="Manual"},
            @{Name="MSiSCSI"; StartupType="Manual"},
            @{Name="MapsBroker"; StartupType="AutomaticDelayedStart"},
            @{Name="McpManagementService"; StartupType="Manual"},
            @{Name="MicrosoftEdgeElevationService"; StartupType="Manual"},
            @{Name="MixedRealityOpenXRSvc"; StartupType="Manual"},
            @{Name="MpsSvc"; StartupType="Automatic"},
            @{Name="MsKeyboardFilter"; StartupType="Manual"},
            @{Name="NaturalAuthentication"; StartupType="Manual"},
            @{Name="NcaSvc"; StartupType="Manual"},
            @{Name="NcbService"; StartupType="Manual"},
            @{Name="NcdAutoSetup"; StartupType="Manual"},
            @{Name="NetSetupSvc"; StartupType="Manual"},
            @{Name="NetTcpPortSharing"; StartupType="Disabled"},
            @{Name="Netlogon"; StartupType="Automatic"},
            @{Name="Netman"; StartupType="Manual"},
            @{Name="NgcCtnrSvc"; StartupType="Manual"},
            @{Name="NgcSvc"; StartupType="Manual"},
            @{Name="NlaSvc"; StartupType="Manual"},
            @{Name="PNRPAutoReg"; StartupType="Manual"},
            @{Name="PNRPsvc"; StartupType="Manual"},
            @{Name="PcaSvc"; StartupType="Manual"},
            @{Name="PeerDistSvc"; StartupType="Manual"},
            @{Name="PerfHost"; StartupType="Manual"},
            @{Name="PhoneSvc"; StartupType="Manual"},
            @{Name="PlugPlay"; StartupType="Manual"},
            @{Name="PolicyAgent"; StartupType="Manual"},
            @{Name="Power"; StartupType="Automatic"},
            @{Name="PrintNotify"; StartupType="Manual"},
            @{Name="ProfSvc"; StartupType="Automatic"},
            @{Name="PushToInstall"; StartupType="Manual"},
            @{Name="QWAVE"; StartupType="Manual"},
            @{Name="RasAuto"; StartupType="Manual"},
            @{Name="RasMan"; StartupType="Manual"},
            @{Name="RemoteAccess"; StartupType="Disabled"},
            @{Name="RemoteRegistry"; StartupType="Disabled"},
            @{Name="RetailDemo"; StartupType="Manual"},
            @{Name="RmSvc"; StartupType="Manual"},
            @{Name="RpcEptMapper"; StartupType="Automatic"},
            @{Name="RpcLocator"; StartupType="Manual"},
            @{Name="RpcSs"; StartupType="Automatic"},
            @{Name="SCPolicySvc"; StartupType="Manual"},
            @{Name="SCardSvr"; StartupType="Manual"},
            @{Name="SDRSVC"; StartupType="Manual"},
            @{Name="SEMgrSvc"; StartupType="Manual"},
            @{Name="SENS"; StartupType="Automatic"},
            @{Name="SNMPTRAP"; StartupType="Manual"},
            @{Name="SNMPTrap"; StartupType="Manual"},
            @{Name="SSDPSRV"; StartupType="Manual"},
            @{Name="SamSs"; StartupType="Automatic"},
            @{Name="ScDeviceEnum"; StartupType="Manual"},
            @{Name="Schedule"; StartupType="Automatic"},
            @{Name="SecurityHealthService"; StartupType="Manual"},
            @{Name="Sense"; StartupType="Manual"},
            @{Name="SensorDataService"; StartupType="Manual"},
            @{Name="SensorService"; StartupType="Manual"},
            @{Name="SensrSvc"; StartupType="Manual"},
            @{Name="SessionEnv"; StartupType="Manual"},
            @{Name="SharedAccess"; StartupType="Manual"},
            @{Name="SharedRealitySvc"; StartupType="Manual"},
            @{Name="ShellHWDetection"; StartupType="Automatic"},
            @{Name="SmsRouter"; StartupType="Manual"},
            @{Name="Spooler"; StartupType="Automatic"},
            @{Name="SstpSvc"; StartupType="Manual"},
            @{Name="StiSvc"; StartupType="Manual"},
            @{Name="StorSvc"; StartupType="Manual"},
            @{Name="SysMain"; StartupType="Automatic"},
            @{Name="SystemEventsBroker"; StartupType="Automatic"},
            @{Name="TabletInputService"; StartupType="Manual"},
            @{Name="TapiSrv"; StartupType="Manual"},
            @{Name="TermService"; StartupType="Automatic"},
            @{Name="Themes"; StartupType="Automatic"},
            @{Name="TieringEngineService"; StartupType="Manual"},
            @{Name="TimeBroker"; StartupType="Manual"},
            @{Name="TimeBrokerSvc"; StartupType="Manual"},
            @{Name="TokenBroker"; StartupType="Manual"},
            @{Name="TrkWks"; StartupType="Automatic"},
            @{Name="TroubleshootingSvc"; StartupType="Manual"},
            @{Name="TrustedInstaller"; StartupType="Manual"},
            @{Name="UI0Detect"; StartupType="Manual"},
            @{Name="UevAgentService"; StartupType="Disabled"},
            @{Name="UmRdpService"; StartupType="Manual"},
            @{Name="UserManager"; StartupType="Automatic"},
            @{Name="UsoSvc"; StartupType="Manual"},
            @{Name="VGAuthService"; StartupType="Automatic"},
            @{Name="VMTools"; StartupType="Automatic"},
            @{Name="VSS"; StartupType="Manual"},
            @{Name="VacSvc"; StartupType="Manual"},
            @{Name="VaultSvc"; StartupType="Automatic"},
            @{Name="W32Time"; StartupType="Manual"},
            @{Name="WEPHOSTSVC"; StartupType="Manual"},
            @{Name="WFDSConMgrSvc"; StartupType="Manual"},
            @{Name="WMPNetworkSvc"; StartupType="Manual"},
            @{Name="WManSvc"; StartupType="Manual"},
            @{Name="WPDBusEnum"; StartupType="Manual"},
            @{Name="WSService"; StartupType="Manual"},
            @{Name="WSearch"; StartupType="AutomaticDelayedStart"},
            @{Name="WaaSMedicSvc"; StartupType="Manual"},
            @{Name="WalletService"; StartupType="Manual"},
            @{Name="WarpJITSvc"; StartupType="Manual"},
            @{Name="WbioSrvc"; StartupType="Manual"},
            @{Name="Wcmsvc"; StartupType="Automatic"},
            @{Name="WcsPlugInService"; StartupType="Manual"},
            @{Name="WdNisSvc"; StartupType="Manual"},
            @{Name="WdiServiceHost"; StartupType="Manual"},
            @{Name="WdiSystemHost"; StartupType="Manual"},
            @{Name="WebClient"; StartupType="Manual"},
            @{Name="Wecsvc"; StartupType="Manual"},
            @{Name="WerSvc"; StartupType="Manual"},
            @{Name="WiaRpc"; StartupType="Manual"},
            @{Name="WinDefend"; StartupType="Automatic"},
            @{Name="WinHttpAutoProxySvc"; StartupType="Manual"},
            @{Name="WinRM"; StartupType="Manual"},
            @{Name="Winmgmt"; StartupType="Automatic"},
            @{Name="WlanSvc"; StartupType="Automatic"},
            @{Name="WpcMonSvc"; StartupType="Manual"},
            @{Name="WpnService"; StartupType="Manual"},
            @{Name="XblAuthManager"; StartupType="Manual"},
            @{Name="XblGameSave"; StartupType="Manual"},
            @{Name="XboxGipSvc"; StartupType="Manual"},
            @{Name="XboxNetApiSvc"; StartupType="Manual"},
            @{Name="autotimesvc"; StartupType="Manual"},
            @{Name="bthserv"; StartupType="Manual"},
            @{Name="camsvc"; StartupType="Manual"},
            @{Name="cloudidsvc"; StartupType="Manual"},
            @{Name="dcsvc"; StartupType="Manual"},
            @{Name="defragsvc"; StartupType="Manual"},
            @{Name="diagnosticshub.standardcollector.service"; StartupType="Manual"},
            @{Name="diagsvc"; StartupType="Manual"},
            @{Name="dmwappushservice"; StartupType="Manual"},
            @{Name="dot3svc"; StartupType="Manual"},
            @{Name="edgeupdate"; StartupType="Manual"},
            @{Name="edgeupdatem"; StartupType="Manual"},
            @{Name="embeddedmode"; StartupType="Manual"},
            @{Name="fdPHost"; StartupType="Manual"},
            @{Name="fhsvc"; StartupType="Manual"},
            @{Name="gpsvc"; StartupType="Automatic"},
            @{Name="hidserv"; StartupType="Manual"},
            @{Name="icssvc"; StartupType="Manual"},
            @{Name="iphlpsvc"; StartupType="Automatic"},
            @{Name="lfsvc"; StartupType="Manual"},
            @{Name="lltdsvc"; StartupType="Manual"},
            @{Name="lmhosts"; StartupType="Manual"},
            @{Name="mpssvc"; StartupType="Automatic"},
            @{Name="msiserver"; StartupType="Manual"},
            @{Name="netprofm"; StartupType="Manual"},
            @{Name="nsi"; StartupType="Automatic"},
            @{Name="p2pimsvc"; StartupType="Manual"},
            @{Name="p2psvc"; StartupType="Manual"},
            @{Name="perceptionsimulation"; StartupType="Manual"},
            @{Name="pla"; StartupType="Manual"},
            @{Name="seclogon"; StartupType="Manual"},
            @{Name="shpamsvc"; StartupType="Disabled"},
            @{Name="smphost"; StartupType="Manual"},
            @{Name="spectrum"; StartupType="Manual"},
            @{Name="sppsvc"; StartupType="AutomaticDelayedStart"},
            @{Name="ssh-agent"; StartupType="Disabled"},
            @{Name="svsvc"; StartupType="Manual"},
            @{Name="swprv"; StartupType="Manual"},
            @{Name="tiledatamodelsvc"; StartupType="Automatic"},
            @{Name="tzautoupdate"; StartupType="Disabled"},
            @{Name="uhssvc"; StartupType="Disabled"},
            @{Name="upnphost"; StartupType="Manual"},
            @{Name="vds"; StartupType="Manual"},
            @{Name="vm3dservice"; StartupType="Manual"},
            @{Name="vmicguestinterface"; StartupType="Manual"},
            @{Name="vmicheartbeat"; StartupType="Manual"},
            @{Name="vmickvpexchange"; StartupType="Manual"},
            @{Name="vmicrdv"; StartupType="Manual"},
            @{Name="vmicshutdown"; StartupType="Manual"},
            @{Name="vmictimesync"; StartupType="Manual"},
            @{Name="vmicvmsession"; StartupType="Manual"},
            @{Name="vmicvss"; StartupType="Manual"},
            @{Name="vmvss"; StartupType="Manual"},
            @{Name="wbengine"; StartupType="Manual"},
            @{Name="wcncsvc"; StartupType="Manual"},
            @{Name="webthreatdefsvc"; StartupType="Manual"},
            @{Name="wercplsupport"; StartupType="Manual"},
            @{Name="wisvc"; StartupType="Manual"},
            @{Name="wlidsvc"; StartupType="Manual"},
            @{Name="wlpasvc"; StartupType="Manual"},
            @{Name="wmiApSrv"; StartupType="Manual"},
            @{Name="workfolderssvc"; StartupType="Manual"},
            @{Name="wscsvc"; StartupType="AutomaticDelayedStart"},
            @{Name="wuauserv"; StartupType="Manual"},
            @{Name="wudfsvc"; StartupType="Manual"}
        )

        foreach ($serviceConfig in $services) {
            $serviceName = $serviceConfig.Name
            $startupType = $serviceConfig.StartupType
            
            try {
                $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
                if ($service) {
                    if ($service.Status -eq 'Running' -and ($startupType -eq 'Disabled' -or $startupType -eq 'Manual')) {
                        Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
                    }
                    
                    Set-Service -Name $serviceName -StartupType $startupType -ErrorAction SilentlyContinue
                }
            } catch {
                # ignore errors for services that don't exist or can't be modified
            }
        }

        $userServices = @(
            "BcastDVRUserService_*", "BluetoothUserService_*", "CDPUserSvc_*", "CaptureService_*",
            "ConsentUxUserSvc_*", "CredentialEnrollmentManagerUserSvc_*", "DeviceAssociationBrokerSvc_*",
            "DevicePickerUserSvc_*", "DevicesFlowUserSvc_*", "MessagingService_*", "NPSMSvc_*",
            "OneSyncSvc_*", "P9RdrService_*", "PenService_*", "PimIndexMaintenanceSvc_*",
            "PrintWorkflowUserSvc_*", "UdkUserSvc_*", "UnistoreSvc_*", "UserDataSvc_*",
            "WpnUserService_*", "cbdhsvc_*", "webthreatdefusersvc_*"
        )

        foreach ($userServicePattern in $userServices) {
            try {
                $userServicesFound = Get-Service -Name $userServicePattern -ErrorAction SilentlyContinue
                foreach ($userService in $userServicesFound) {
                    $targetStartupType = "Manual"
                    if ($userServicePattern -eq "CDPUserSvc_*" -or $userServicePattern -eq "OneSyncSvc_*" -or 
                        $userServicePattern -eq "WpnUserService_*" -or $userServicePattern -eq "webthreatdefusersvc_*") {
                        $targetStartupType = "Automatic"
                    }
                    
                    if ($userService.Status -eq 'Running' -and $targetStartupType -eq "Manual") {
                        Stop-Service -Name $userService.Name -Force -ErrorAction SilentlyContinue
                    }
                    
                    Set-Service -Name $userService.Name -StartupType $targetStartupType -ErrorAction SilentlyContinue
                }
            } catch {}
        }
    } catch {
        return 0
    }
    return 1
}

return (TweakServices)